import "./index.css";
import { ActivityComposition } from "./ActivityComposition";
import { Composition } from "remotion";
import { gql, request } from "graphql-request";

import moment from "moment";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { loadFont } from "@remotion/fonts";
import { staticFile } from "remotion";
import { StartComposition } from "./StartComposition";
import { WEEK } from "./HelloWorld/constants";

const queryClient = new QueryClient();

// Generated by https://quicktype.io

export interface Result {
  activities: Activities;
}

export interface Activities {
  results: Activity[];
}

export interface Activity {
  summary: string;
  location: string;
  begin: Date;
  end: Date;
  imageIcon: string;
  enrollment: boolean;
  absoluteUrl: string;
  activityLabel: ActivityLabel;
  price: string;
}

export interface ActivityLabel {
  name: string;
  color: string;
}

export const RemotionRoot: React.FC = () => {
  const fps = 30;
  return (
    <>
      <QueryClientProvider client={queryClient}>
        <Composition
          // You can take the "id" to render a video:
          // npx remotion render HelloWorld
          id="ActivityComposition"
          component={ActivityComposition}
          durationInFrames={fps * 6}
          fps={fps}
          width={1080}
          height={1920}
          // You can override these props for each render:
          // https://www.remotion.dev/docs/parametrized-rendering
          defaultProps={{
            data: [],
          }}
          calculateMetadata={async ({ props }) => {
            const res = await fetchActivities();
            return {
              props: {
                ...props,
                data: res,
              },
            };
          }}
        />
        <Composition
          // You can take the "id" to render a video:
          // npx remotion render HelloWorld
          id="StartComposition"
          component={StartComposition}
          durationInFrames={fps * 3.5}
          fps={fps}
          width={1080}
          height={1920}
          // You can override these props for each render:
          // https://www.remotion.dev/docs/parametrized-rendering
          defaultProps={{
            week: WEEK,
          }}
        />
      </QueryClientProvider>
    </>
  );
};

loadFont({
  family: "Gill Sans",
  url: staticFile("Gill Sans.otf"),
  weight: "400",
});

loadFont({
  family: "Gill Sans",
  url: staticFile("Gill Sans Bold.otf"),
  weight: "700",
});

loadFont({
  family: "Gill Sans",
  url: staticFile("Gill Sans Heavy.otf"),
  weight: "900",
});

loadFont({
  family: "Gill Sans",
  url: staticFile("Gill Sans Light.otf"),
  weight: "300",
});

loadFont({
  family: "Gill Sans",
  url: staticFile("Gill Sans Medium.otf"),
  weight: "500",
});

async function fetchActivities(): Promise<Activity[]> {
  const week = moment("2026W" + WEEK);

  const start = week.startOf("week").toISOString();
  const end = week.endOf("week").toISOString();

  const res: Result = await request(
    "https://www.inter-actief.utwente.nl/graphql/",
    gql`
      query UpcomingActivities($start: DateTime, $end: DateTime) {
        activities(begin_Gt: $start, begin_Lt: $end) {
          results {
            summary
            location
            begin
            end
            imageIcon
            enrollment
            absoluteUrl
            activityLabel {
              name
              color
            }
            price
          }
        }
      }
    `,
    {
      end: end,
      start: start,
    },
  ).catch((error) => {
    console.error("Error fetching data for upcoming activities:", error);
    return {
      activities: {
        results: [],
      },
    };
  });
  console.log("Fetched data for upcoming activities:", res);
  return res.activities.results;
  // ...
}
