import "./index.css";
import { ActivityComposition } from "./ActivityComposition";
import { Composition } from "remotion";
// import { gql, request } from "graphql-request";

// import moment from "moment";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { loadFont } from "@remotion/fonts";
import { staticFile } from "remotion";
import { StartComposition } from "./StartComposition";
import { WEEK } from "./HelloWorld/constants";
import activities from "./activities.json";
const queryClient = new QueryClient();

// Generated by https://quicktype.io

export interface Result {
  activities: Activities;
}

export interface Activities {
  results: Activity[];
}

export interface Activity {
  summary: string;
  location: string;
  begin: string;
  end: string;
  imageIcon: string;
  enrollment: boolean;
  absoluteUrl: string;
  activityLabel: ActivityLabel;
  price: string;
}

export interface ActivityLabel {
  name: string;
  color: string;
}

export const RemotionRoot: React.FC = () => {
  const fps = 30;
  return (
    <>
      <QueryClientProvider client={queryClient}>
        <Composition
          id="ActivityComposition"
          component={ActivityComposition}
          durationInFrames={fps * 6}
          fps={fps}
          width={1080}
          height={1920}
          defaultProps={{
            data: activities,
          }}
        />
        <Composition
          id="StartComposition"
          component={StartComposition}
          durationInFrames={fps * 3.5}
          fps={fps}
          width={1080}
          height={1920}
          defaultProps={{
            week: WEEK,
          }}
        />
      </QueryClientProvider>
    </>
  );
};

loadFont({
  family: "Gill Sans",
  url: staticFile("Gill Sans.otf"),
  weight: "400",
});

loadFont({
  family: "Gill Sans",
  url: staticFile("Gill Sans Bold.otf"),
  weight: "700",
});

loadFont({
  family: "Gill Sans",
  url: staticFile("Gill Sans Heavy.otf"),
  weight: "900",
});

loadFont({
  family: "Gill Sans",
  url: staticFile("Gill Sans Light.otf"),
  weight: "300",
});

loadFont({
  family: "Gill Sans",
  url: staticFile("Gill Sans Medium.otf"),
  weight: "500",
});
